export const STRINGS = {
  ta: {
    brand: 'குரோம்பேட்டை கார்காத்தார் சங்கம்',
    event: 'மங்கல சந்திப்பு',
    lang_switch: 'English',
    skip: 'முதன்மை உள்ளடக்கத்திற்குச் செல்',
    loading: 'ஏற்றுகிறது…',
    save: 'சேமி', cancel: 'ரத்து', edit: 'திருத்து', delete: 'நீக்கு', back: 'பின்செல்', search: 'தேடு', all: 'அனைத்தும்',
    prev: 'முந்தையது', next: 'அடுத்தது', home: 'முகப்பு', yes: 'ஆம்', no: 'இல்லை',

    hero_tag: 'கார்காத்தார் சமூகத்தினருக்கான திருமணத் தகவல் சந்திப்பு',
    edition: '19-ம் ஆண்டு',
    last_date_label: 'பதிவு செய்ய கடைசி நாள்',
    last_date: '15 டிசம்பர் 2026',
    event_on: 'நிகழ்ச்சி நாள்',
    notice_title: 'முக்கிய அறிவிப்பு',
    notice_text: 'கட்டணம் செலுத்தி, முழுமையாக நிரப்பி சமர்ப்பிக்கப்பட்ட விண்ணப்பங்கள் மட்டுமே ஏற்றுக்கொள்ளப்படும்.',
    apply_btn: 'இப்போதே விண்ணப்பிக்கவும்',
    pay_note: 'இந்த படிவத்தை நிறைவு செய்ய பணம் செலுத்திய விவரம் தேவை.',
    apply_note: 'விண்ணப்பப் படிவம் தமிழில் மட்டுமே உள்ளது.',
    when: 'தேதி', where: 'இடம்',
    date_tba: 'விரைவில் அறிவிக்கப்படும்',
    steps_title: 'விண்ணப்பிப்பது எப்படி',
    step1: 'விதிமுறைகளைப் படித்து ஏற்கவும்',
    step2: 'பதிவு கட்டணத்தை வங்கிக் கணக்கில் செலுத்தவும்',
    step3: 'படிவத்தை முழுமையாக நிரப்பி சமர்ப்பிக்கவும்',
    step4: 'தனித்துவமான பதிவு எண்ணைப் பெறுங்கள்',
    bank_title: 'கட்டண விவரம்',
    bank_acc: 'கணக்கு எண்',
    bank_fee: 'பதிவு கட்டணம்',
    contact_title: 'தொடர்புக்கு',
    staff_login: 'நிர்வாகி உள்நுழைவு',

    login_title: 'நிர்வாக உள்நுழைவு',
    username: 'பயனர் பெயர்', password: 'கடவுச்சொல்',
    sign_in: 'உள்நுழை', sign_out: 'வெளியேறு',
    nav_dashboard: 'டாஷ்போர்டு', nav_apps: 'விண்ணப்பங்கள்', nav_users: 'பயனர்கள்', nav_settings: 'அமைப்புகள்',
    settings_title: 'தள அமைப்புகள்',
    s_event: 'நிகழ்வு விவரம்', s_payment: 'கட்டண விவரம்',
    s_event_date: 'தேதி', s_event_date_ph: 'DD-MM-YYYY, எ.கா. 27-12-2026 (கிழமை தானாகச் சேர்க்கப்படும்)',
    s_venue_ta: 'இடம் (தமிழ்)', s_venue_en: 'இடம் (ஆங்கிலம்)',
    s_bank_name: 'வங்கி பெயர் (கிளையுடன், தமிழ்)', s_bank_name_en: 'வங்கி பெயர் (கிளையுடன், ஆங்கிலம்)', s_bank_account: 'கணக்கு எண்', s_bank_ifsc: 'IFSC குறியீடு',
    s_qr: 'QR குறியீடு', s_qr_current: 'தற்போதைய QR', s_qr_upload: 'படம் தேர்ந்தெடு', s_qr_remove: 'QR-ஐ நீக்கு',
    s_qr_hint: 'PNG / JPG / WEBP, 2MB வரை.',
    s_saved: 'சேமிக்கப்பட்டது.',
    e_too_large: 'கோப்பு மிகப் பெரியது (2MB வரை மட்டும்).',
    role_admin: 'நிர்வாகி', role_manager: 'மேலாளர்',
    st_pending: 'நிலுவையில்', st_accepted: 'ஏற்கப்பட்டது', st_rejected: 'நிராகரிக்கப்பட்டது',
    d_total: 'மொத்த விண்ணப்பங்கள்', d_accepted: 'ஏற்கப்பட்ட விண்ணப்பங்கள்',
    d_rejected: 'நிராகரிக்கப்பட்ட விண்ணப்பங்கள்', d_pending: 'நிலுவையில் உள்ள விண்ணப்பங்கள்',
    d_male: 'ஆண்', d_female: 'பெண்',
    a_reg: 'பதிவு எண்', a_name: 'பெயர்', a_phone: 'தொலைபேசி', a_status: 'நிலை', a_gender: 'பாலினம்', a_date: 'சமர்ப்பித்த நாள்',
    a_search_ph: 'பெயர், பதிவு எண், தொலைபேசி, UTR…',
    a_none: 'விண்ணப்பங்கள் இல்லை.',
    page_of: 'பக்கம் {p} / {n}', a_total: 'மொத்தம்: {n}',
    v_edit: 'விண்ணப்பத்தைத் திருத்து', v_saved: 'சேமிக்கப்பட்டது.',
    v_locked: 'முடிவு எடுக்கப்பட்ட விண்ணப்பத்தை நிர்வாகி மட்டுமே மாற்ற முடியும்.',
    v_decision: 'முடிவு', v_accept: 'ஏற்றுக்கொள்', v_reject: 'நிராகரி', v_reset: 'நிலுவைக்கு மாற்று',
    v_note: 'குறிப்பு', v_note_hint: 'நிராகரிக்கும்போது காரணம் அவசியம்.',
    v_confirm: 'இந்த முடிவை உறுதி செய்யவா?',
    v_decided_by: 'முடிவெடுத்தவர்', v_history: 'வரலாறு',
    h_created: 'சமர்ப்பிக்கப்பட்டது', h_edited: 'திருத்தப்பட்டது', h_decision: 'முடிவு', v_system: 'விண்ணப்பதாரர்',
    v_paid: 'செலுத்திய தொகை', v_terms: 'விதிமுறைகள் ஏற்ற நேரம்', v_regno: 'பதிவு எண்', v_submitted: 'சமர்ப்பித்த நேரம்',
    users_title: 'பயனர் மேலாண்மை', u_new: 'புதிய பயனர்', u_edit: 'பயனரைத் திருத்து',
    u_name: 'பெயர்', u_role: 'பங்கு', u_active: 'செயலில்', u_inactive: 'முடக்கப்பட்டது', u_last: 'கடைசி உள்நுழைவு',
    u_pass_new: 'குறைந்தது 10 எழுத்துகள்', u_pass_edit: 'மாற்ற வேண்டுமெனில் மட்டும் உள்ளிடவும்',
    u_delete_confirm: 'இந்த பயனரை நீக்கவா?', u_never: 'இதுவரை இல்லை', u_status: 'நிலை',

    a_assignee: 'ஒதுக்கப்பட்டவர்', a_unassigned: 'ஒதுக்கப்படவில்லை', a_mine: 'எனக்கு ஒதுக்கப்பட்டவை', a_assign_filter: 'ஒதுக்கீடு',
    asg_title: 'விண்ணப்பங்களை ஒதுக்கு', asg_manager: 'மேலாளர்', asg_count: 'விண்ணப்பங்களின் எண்ணிக்கை', asg_choose: 'மேலாளரைத் தேர்ந்தெடுக்கவும்',
    asg_go: 'ஒதுக்கு', asg_available: 'ஒதுக்கப்படாத நிலுவை விண்ணப்பங்கள்: {n}',
    asg_hint: 'ஒதுக்கப்படாத பழைய நிலுவை விண்ணப்பங்கள் முதலில் ஒதுக்கப்படும்.',
    asg_done: '{n} விண்ணப்பம்(ங்கள்) {name} அவர்களுக்கு ஒதுக்கப்பட்டன.',
    asg_partial: 'ஒதுக்கப்படாத {n} விண்ணப்பம்(ங்கள்) மட்டுமே இருந்தன; அனைத்தும் {name} அவர்களுக்கு ஒதுக்கப்பட்டன.',
    asg_load: 'நிலுவை: {n}',
    v_assignment: 'ஒதுக்கீடு', v_assigned_to: 'ஒதுக்கப்பட்டவர்', v_assigned_by: 'ஒதுக்கியவர்', v_unassigned: 'ஒதுக்கப்படவில்லை',
    v_assign: 'ஒதுக்கு', v_reassign: 'மாற்றி ஒதுக்கு', v_unassign: 'ஒதுக்கீட்டை நீக்கு',
    v_only_assignee: '{name} (அல்லது நிர்வாகி) மட்டுமே இந்த விண்ணப்பத்தை ஏற்கவோ நிராகரிக்கவோ முடியும். அனைத்து மேலாளர்களும் இதைப் பார்க்கவும் திருத்தவும் முடியும்.',
    v_unassigned_info: 'இந்த விண்ணப்பம் இன்னும் ஒதுக்கப்படவில்லை. ஏற்க அல்லது நிராகரிக்க நிர்வாகி இதை ஒரு மேலாளருக்கு ஒதுக்க வேண்டும். அனைத்து மேலாளர்களும் இதைப் பார்க்கவும் திருத்தவும் முடியும்.',
    h_assigned: 'ஒதுக்கப்பட்டது', h_unassigned: 'ஒதுக்கீடு நீக்கப்பட்டது',
    d_unassigned: 'ஒதுக்கப்படாத நிலுவை', d_mine: 'எனக்கு ஒதுக்கப்பட்டவை (நிலுவை)',
    e_not_assigned: 'இந்த விண்ணப்பம் யாருக்கு ஒதுக்கப்பட்டுள்ளதோ அந்த மேலாளர் மட்டுமே ஏற்கவோ நிராகரிக்கவோ முடியும்.',
    e_not_pending: 'நிலுவையில் உள்ள விண்ணப்பங்களை மட்டுமே ஒதுக்க முடியும்.',
    e_none_available: 'ஒதுக்கப்படாத நிலுவை விண்ணப்பங்கள் இல்லை.',

    h_details: 'மாற்றங்களைக் காட்டு', h_field: 'புலம்', h_before: 'முன்', h_after: 'பின்',
    f_summary: 'படிவத்தில் பிழைகள் உள்ளன. குறிக்கப்பட்ட இடங்களைச் சரிசெய்யவும்.',
    e_invalid_credentials: 'பயனர் பெயர் அல்லது கடவுச்சொல் தவறு.',
    e_throttled: 'பல முறை முயற்சிக்கப்பட்டது. சிறிது நேரம் கழித்து மீண்டும் முயற்சிக்கவும்.',
    e_locked: 'முடிவு எடுக்கப்பட்ட விண்ணப்பத்தை நிர்வாகி மட்டுமே மாற்ற முடியும்.',
    e_conflict: 'வேறொருவர் ஏற்கனவே இதை மாற்றியுள்ளார். பக்கத்தைப் புதுப்பிக்கவும்.',
    e_no_change: 'நிலையில் மாற்றம் இல்லை.',
    e_forbidden: 'இதற்கு அனுமதி இல்லை.',
    e_unauthorized: 'மீண்டும் உள்நுழையவும்.',
    e_csrf: 'அமர்வு காலாவதியானது. பக்கத்தைப் புதுப்பித்து மீண்டும் முயற்சிக்கவும்.',
    e_self_protect: 'உங்கள் சொந்த கணக்கை முடக்கவோ நீக்கவோ பங்கை மாற்றவோ முடியாது.',
    e_not_found: 'கிடைக்கவில்லை.',
    e_server: 'சேவையகப் பிழை. சிறிது நேரம் கழித்து மீண்டும் முயற்சிக்கவும்.',
    e_network: 'இணைய இணைப்பைச் சரிபார்க்கவும்.',
    e_bad_request: 'தவறான கோரிக்கை.',
    e_validation: 'படிவத்தில் உள்ள பிழைகளைச் சரிசெய்யவும்.',
    e_required: 'இந்த விவரம் அவசியம்.',
    e_invalid: 'சரியான மதிப்பை உள்ளிடவும்.',
    e_too_long: 'உள்ளீடு மிக நீளமாக உள்ளது.',
    e_age_min: 'குறைந்தபட்சம் 18 வயது நிரம்பியிருக்க வேண்டும்.',
    e_date_format: 'தேதியை DD-MM-YYYY வடிவில் உள்ளிடவும் (எ.கா. 01-01-2000).',
    w_age_18_21: 'வயது 18-21 இடையே உள்ளது. உறுதிசெய்து தொடரவும்.',
    e_future_date: 'எதிர்காலத் தேதி அனுமதிக்கப்படாது.',
    e_duplicate: 'இந்த மதிப்பு ஏற்கனவே பதிவு செய்யப்பட்டுள்ளது.',
    e_weak: 'கடவுச்சொல் குறைந்தது 10 எழுத்துகள் இருக்க வேண்டும்.',
  },
  en: {
    brand: 'Chromepet Karkathar Sangam',
    event: 'Mangala Santhippu (Marriage Meet)',
    lang_switch: 'தமிழ்',
    skip: 'Skip to main content',
    loading: 'Loading…',
    save: 'Save', cancel: 'Cancel', edit: 'Edit', delete: 'Delete', back: 'Back', search: 'Search', all: 'All',
    prev: 'Previous', next: 'Next', home: 'Home', yes: 'Yes', no: 'No',

    hero_tag: 'A marriage information meet for the Karkathar community',
    edition: '19th year',
    last_date_label: 'Last date to register',
    last_date: '15 December 2026',
    event_on: 'Event date',
    bank_acc: 'A/c No.',
    notice_title: 'Important notice',
    notice_text: 'Only paid and fully submitted applications will be accepted.',
    apply_btn: 'Apply now',
    pay_note: 'To complete this form, payment details are required.',
    apply_note: 'The application form is available in Tamil only.',
    when: 'Date', where: 'Venue',
    date_tba: 'To be announced',
    steps_title: 'How to apply',
    step1: 'Read and accept the terms',
    step2: 'Pay the registration fee to the bank account',
    step3: 'Fill in the form completely and submit',
    step4: 'Receive your unique registration number',
    bank_title: 'Payment details',
    bank_fee: 'Registration fee',
    contact_title: 'Contact',
    staff_login: 'Staff login',

    login_title: 'Staff sign in',
    username: 'Username', password: 'Password',
    sign_in: 'Sign in', sign_out: 'Sign out',
    nav_dashboard: 'Dashboard', nav_apps: 'Applications', nav_users: 'Users', nav_settings: 'Settings',
    settings_title: 'Site settings',
    s_event: 'Event details', s_payment: 'Payment details',
    s_event_date: 'Date', s_event_date_ph: 'DD-MM-YYYY, e.g. 27-12-2026 (weekday is added automatically)',
    s_venue_ta: 'Venue (Tamil)', s_venue_en: 'Venue (English)',
    s_bank_name: 'Bank name (with branch, Tamil)', s_bank_name_en: 'Bank name (with branch, English)', s_bank_account: 'Account number', s_bank_ifsc: 'IFSC code',
    s_qr: 'QR code', s_qr_current: 'Current QR', s_qr_upload: 'Choose image', s_qr_remove: 'Remove QR',
    s_qr_hint: 'PNG / JPG / WEBP, up to 2MB.',
    s_saved: 'Saved.',
    e_too_large: 'File is too large (2MB max).',
    role_admin: 'Admin', role_manager: 'Manager',
    st_pending: 'Pending', st_accepted: 'Accepted', st_rejected: 'Rejected',
    d_total: 'Total applications', d_accepted: 'Accepted applications',
    d_rejected: 'Rejected applications', d_pending: 'Pending applications',
    d_male: 'Male', d_female: 'Female',
    a_reg: 'Reg. No.', a_name: 'Name', a_phone: 'Phone', a_status: 'Status', a_gender: 'Gender', a_date: 'Submitted',
    a_search_ph: 'Name, reg. no., phone, UTR…',
    a_none: 'No applications found.',
    page_of: 'Page {p} of {n}', a_total: 'Total: {n}',
    v_edit: 'Edit application', v_saved: 'Saved.',
    v_locked: 'A decided application can be changed by an admin only.',
    v_decision: 'Decision', v_accept: 'Accept', v_reject: 'Reject', v_reset: 'Reset to pending',
    v_note: 'Note', v_note_hint: 'A reason is required when rejecting.',
    v_confirm: 'Confirm this decision?',
    v_decided_by: 'Decided by', v_history: 'History',
    h_created: 'Submitted', h_edited: 'Edited', h_decision: 'Decision', v_system: 'Applicant',
    v_paid: 'Amount paid', v_terms: 'Terms accepted at', v_regno: 'Registration no.', v_submitted: 'Submitted at',
    users_title: 'User management', u_new: 'New user', u_edit: 'Edit user',
    u_name: 'Name', u_role: 'Role', u_active: 'Active', u_inactive: 'Disabled', u_last: 'Last login',
    u_pass_new: 'At least 10 characters', u_pass_edit: 'Leave blank to keep the current password',
    u_delete_confirm: 'Delete this user?', u_never: 'Never', u_status: 'Status',

    a_assignee: 'Assigned to', a_unassigned: 'Unassigned', a_mine: 'Assigned to me', a_assign_filter: 'Assignment',
    asg_title: 'Assign applications', asg_manager: 'Manager', asg_count: 'Number of applications', asg_choose: 'Select a manager',
    asg_go: 'Assign', asg_available: 'Unassigned pending applications: {n}',
    asg_hint: 'The oldest unassigned pending applications are assigned first.',
    asg_done: 'Assigned {n} application(s) to {name}.',
    asg_partial: 'Only {n} unassigned application(s) were available; all of them were assigned to {name}.',
    asg_load: 'Pending: {n}',
    v_assignment: 'Assignment', v_assigned_to: 'Assigned to', v_assigned_by: 'Assigned by', v_unassigned: 'Not assigned',
    v_assign: 'Assign', v_reassign: 'Reassign', v_unassign: 'Unassign',
    v_only_assignee: 'Only {name} (or an admin) can accept or reject this application. All managers can view and edit it.',
    v_unassigned_info: 'This application is not assigned yet. An admin must assign it to a manager before it can be accepted or rejected. All managers can view and edit it.',
    h_assigned: 'Assigned to', h_unassigned: 'Unassigned from',
    d_unassigned: 'Unassigned pending', d_mine: 'Assigned to me (pending)',
    e_not_assigned: 'Only the manager this application is assigned to can accept or reject it.',
    e_not_pending: 'Only pending applications can be assigned.',
    e_none_available: 'There are no unassigned pending applications.',

    h_details: 'Show changes', h_field: 'Field', h_before: 'Before', h_after: 'After',
    f_summary: 'The form has errors. Please fix the marked fields.',
    e_invalid_credentials: 'Incorrect username or password.',
    e_throttled: 'Too many attempts. Please try again later.',
    e_locked: 'A decided application can be changed by an admin only.',
    e_conflict: 'Someone else has already changed this. Please refresh the page.',
    e_no_change: 'The status is unchanged.',
    e_forbidden: 'You are not allowed to do this.',
    e_unauthorized: 'Please sign in again.',
    e_csrf: 'Session expired. Refresh the page and try again.',
    e_self_protect: 'You cannot disable, delete or change the role of your own account.',
    e_not_found: 'Not found.',
    e_server: 'Server error. Please try again shortly.',
    e_network: 'Please check your internet connection.',
    e_bad_request: 'Invalid request.',
    e_validation: 'Please fix the errors in the form.',
    e_required: 'This field is required.',
    e_invalid: 'Enter a valid value.',
    e_too_long: 'The input is too long.',
    e_age_min: 'Must be at least 18 years old.',
    e_date_format: 'Enter the date as DD-MM-YYYY (e.g. 01-01-2000).',
    w_age_18_21: 'Age is between 18 and 21 — please confirm before proceeding.',
    e_future_date: 'A future date is not allowed.',
    e_duplicate: 'This value is already registered.',
    e_weak: 'Password must be at least 10 characters.',
  },
};
